package sv.udb.alumno.mediateca_GUI;

import java.awt.CardLayout;
import javax.swing.*;


public class Mediateca_GUI extends javax.swing.JFrame {     
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mediateca_GUI.class.getName());
   
    
// NOMBRES Y  DEFINICION DE LAS VISTAS PARA CARD LAYOUT
    private PanelInicio panelInicio = new PanelInicio();    
    private Modificar_UI modificarUI = new Modificar_UI();
    private Listar_UI listarUI = new Listar_UI();
    private Busqueda_Material_UI buscarUI = new Busqueda_Material_UI();
    private Borrar_UI borrarUI = new Borrar_UI();
    private acercade_UI acercadeUI = new acercade_UI();    
    private Agregar_Libro_UI agregarLibroUI = new Agregar_Libro_UI();
    private Agregar_CD_UI agregarCDUI = new Agregar_CD_UI();
    private Agregar_DVD_UI agregarDVDUI = new Agregar_DVD_UI();
    private Agregar_Revista_UI agregarRevistaUI = new Agregar_Revista_UI();
    
    CardLayout vista;
   
    private static final String CARD_INICIO = "inicio";
    private static final String CARD_AGREGAR_LIBRO = "agregarLibro";
    private static final String CARD_AGREGAR_CD = "agregarCD";
    private static final String CARD_AGREGAR_DVD = "agregarDVD";
    private static final String CARD_AGREGAR_REVISTA = "agregarRevista";
    private static final String CARD_MODIFICAR = "modificar";
    private static final String CARD_LISTAR = "listar";
    private static final String CARD_BUSCAR = "buscar";
    private static final String CARD_BORRAR = "borrar";
    private static final String CARD_ACERCA_DE = "acercaDe";
    
    
    public Mediateca_GUI() {
        initComponents();
        
//  Obtener el CardLayout del PanelPrincipal
        vista = (CardLayout) PanelPrincipal.getLayout();
        
//  AGREGAR LAS VISTAS AL PANEL PRINCIPAL
        PanelPrincipal.add(panelInicio, CARD_INICIO);        
        PanelPrincipal.add(agregarLibroUI, CARD_AGREGAR_LIBRO);
        PanelPrincipal.add(agregarCDUI, CARD_AGREGAR_CD);
        PanelPrincipal.add(agregarDVDUI, CARD_AGREGAR_DVD);
        PanelPrincipal.add(agregarRevistaUI, CARD_AGREGAR_REVISTA);
        PanelPrincipal.add(modificarUI, CARD_MODIFICAR);
        PanelPrincipal.add(listarUI, CARD_LISTAR);
        PanelPrincipal.add(buscarUI, CARD_BUSCAR);
        PanelPrincipal.add(borrarUI, CARD_BORRAR);
        PanelPrincipal.add(acercadeUI, CARD_ACERCA_DE);
        
// Mostrar la pantalla de inicio por defecto
        vista.show(PanelPrincipal, CARD_INICIO);            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        PanelPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mediateca - Sistema de Gestion de Materiales");
        setBackground(new java.awt.Color(0, 102, 255));
        setForeground(new java.awt.Color(0, 102, 204));
        setIconImages(null);
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 768));

        PanelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        PanelPrincipal.setName("VentanaPrincipal"); // NOI18N
        PanelPrincipal.setLayout(new java.awt.CardLayout());

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu1.setText("Material");

        jMenu6.setText("Agregar");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setText("Libro");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu6.add(jMenuItem1);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem10.setText("Revista");
        jMenuItem10.addActionListener(this::jMenuItem10ActionPerformed);
        jMenu6.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem11.setText("CD");
        jMenuItem11.addActionListener(this::jMenuItem11ActionPerformed);
        jMenu6.add(jMenuItem11);

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem12.setText("DVD");
        jMenuItem12.addActionListener(this::jMenuItem12ActionPerformed);
        jMenu6.add(jMenuItem12);

        jMenu1.add(jMenu6);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setText("Modificar");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setText("Listar");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu1.add(jMenuItem3);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem5.setText("Borrar");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu1.add(jMenuItem5);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem4.setText("Buscar");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem8.setText("Inicio");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        jMenu2.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem9.setText("Salir");
        jMenuItem9.addActionListener(this::jMenuItem9ActionPerformed);
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Ayuda");

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem6.setText("Acerca de");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu5.add(jMenuItem6);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelPrincipal.getAccessibleContext().setAccessibleName("VentanaPrincipal");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
//EVENTOS DE BOTONES PRINCIPALES
        
   
// Listado Añadir Libro
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        vista.show(PanelPrincipal, CARD_AGREGAR_LIBRO);
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
// Menu Item Agregar REVISTA    
    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        vista.show(PanelPrincipal, CARD_AGREGAR_REVISTA);
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

// Menu Item Agregar CD
    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        vista.show(PanelPrincipal, CARD_AGREGAR_CD);
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

// Menu Item Agregar DVD
    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        vista.show(PanelPrincipal, CARD_AGREGAR_DVD);
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

// Menu Item MODIFICAR
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        vista.show(PanelPrincipal, CARD_MODIFICAR);
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

// Menu Item LISTAR
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        vista.show(PanelPrincipal, CARD_LISTAR);
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

// Menu Item BORRAR    
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        vista.show(PanelPrincipal, CARD_BORRAR);
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

// Menu Item BUSCAR    
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        vista.show(PanelPrincipal, CARD_BUSCAR);
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuItem4ActionPerformed
// Menu Item INICIO
    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        vista.show(PanelPrincipal, CARD_INICIO);
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

// Menu Item SALIR    
    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Desea salir de la aplicación?",
            "Confirmar Salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );
        
        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

// Menu Item Acerca DE 
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        vista.show(PanelPrincipal, CARD_ACERCA_DE);
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Mediateca_GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
