/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mediateca.vistas.busquedas;

/**
 *
 * @author Francisco De la O Gonzalez - DG200722
 */
public class Panel_BuscaMat extends javax.swing.JPanel {

    /**
     * Creates new form Panel_BuscaMat
     */
    public Panel_BuscaMat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        boton_buscar_material_tabla = new javax.swing.JButton();
        boton_limpiar_campos = new javax.swing.JButton();
        boton_regresar_menu_anterior = new javax.swing.JButton();
        botn_modificar_primerelementolista = new javax.swing.JButton();
        botn_modificar_segndoelementolista = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        combobox_selecciónmaterial_busqueda = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        campo_titulomaterial_busqueda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campo_codigomaterial_busqueda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1075, 655));
        setMinimumSize(new java.awt.Dimension(1075, 655));

        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        boton_buscar_material_tabla.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_buscar_material_tabla.setText("BUSCAR");

        boton_limpiar_campos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_limpiar_campos.setText("LIMPIAR");
        boton_limpiar_campos.addActionListener(this::boton_limpiar_camposActionPerformed);

        boton_regresar_menu_anterior.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_regresar_menu_anterior.setText("CANCELAR");

        botn_modificar_primerelementolista.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botn_modificar_primerelementolista.setText("Modificar");
        botn_modificar_primerelementolista.addActionListener(this::botn_modificar_primerelementolistaActionPerformed);

        botn_modificar_segndoelementolista.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botn_modificar_segndoelementolista.setText("Modificar");

        jButton6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton6.setText("Modificar");

        jButton7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton7.setText("Modificar");

        jButton8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton8.setText("Modificar");

        combobox_selecciónmaterial_busqueda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        combobox_selecciónmaterial_busqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIBRO", "REVISTA", "TESIS", "CD", "DVD" }));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Titulo");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Codigo");

        campo_codigomaterial_busqueda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Tipo");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BUSQUEDA DE MATERIAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combobox_selecciónmaterial_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(campo_titulomaterial_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(69, 69, 69)
                                                .addComponent(jLabel2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(218, 218, 218)
                                                .addComponent(boton_buscar_material_tabla)
                                                .addGap(55, 55, 55)
                                                .addComponent(boton_limpiar_campos)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(boton_regresar_menu_anterior)
                                            .addComponent(campo_codigomaterial_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botn_modificar_segndoelementolista)
                                    .addComponent(botn_modificar_primerelementolista)
                                    .addComponent(jButton6)
                                    .addComponent(jButton7)
                                    .addComponent(jButton8))))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campo_titulomaterial_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(campo_codigomaterial_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox_selecciónmaterial_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_limpiar_campos)
                    .addComponent(boton_buscar_material_tabla)
                    .addComponent(boton_regresar_menu_anterior))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botn_modificar_primerelementolista)
                        .addGap(18, 18, 18)
                        .addComponent(botn_modificar_segndoelementolista)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8)
                        .addGap(132, 132, 132))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boton_limpiar_camposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_limpiar_camposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_limpiar_camposActionPerformed

    private void botn_modificar_primerelementolistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botn_modificar_primerelementolistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botn_modificar_primerelementolistaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botn_modificar_primerelementolista;
    private javax.swing.JButton botn_modificar_segndoelementolista;
    private javax.swing.JButton boton_buscar_material_tabla;
    private javax.swing.JButton boton_limpiar_campos;
    private javax.swing.JButton boton_regresar_menu_anterior;
    private javax.swing.JTextField campo_codigomaterial_busqueda;
    private javax.swing.JTextField campo_titulomaterial_busqueda;
    private javax.swing.JComboBox<String> combobox_selecciónmaterial_busqueda;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
