/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mediateca.vistas;
 
import com.mediateca.dao.UsuarioDAO;
import com.mediateca.model.Usuario;
import com.mediateca.util.SessionManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
 
/**
 *
 * @author Francisco De la O Gonzalez - DG200722
 */
public class Panel_Bienvenida extends javax.swing.JPanel {
 
    private static final Logger logger = Logger.getLogger(Panel_Bienvenida.class.getName());
 
    private final UsuarioDAO usuarioDAO = new UsuarioDAO();
 
    /**
     * Creates new form Panel_Bienvenida
     */
    public Panel_Bienvenida() {
        initComponents();
        cablearEventos();
        label_ayuda.setText(" "); // limpiar el texto "Ayuda" por defecto
    }
 
    private void cablearEventos() {
        boton_login_acceder.addActionListener(e -> hacerLogin());
        // Permitir login con ENTER en el campo de contraseña
        campo_login_password.addActionListener(e -> hacerLogin());
    }
 
    /**
     * Valida las credenciales contra la BD y navega al panel correspondiente
     * segun el tipo de usuario.
     */
    private void hacerLogin() {
        String email = campo_login_carnet.getText().trim();
        String password = new String(campo_login_password.getPassword());
 
        // Validaciones basicas de entrada
        if (email.isEmpty() || password.isEmpty()) {
            mostrarError("Ingrese usuario y contraseña.");
            return;
        }
 
        try {
            if (!usuarioDAO.validarCredenciales(email, password)) {
                mostrarError("Credenciales incorrectas.");
                campo_login_password.setText("");
                return;
            }
 
            Usuario u = usuarioDAO.obtenerPorEmail(email);
            if (u == null) {
                mostrarError("No se pudo cargar el usuario.");
                return;
            }
 
            // Login exitoso: guardar en sesion y navegar
            SessionManager.iniciarSesion(u);
            label_ayuda.setText(" ");
            campo_login_password.setText("");
 
            navegarSegunTipo(u);
 
        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Error inesperado al hacer login", ex);
            JOptionPane.showMessageDialog(this,
                "Error de conexión: " + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
 
    /**
     * Carga el panel correspondiente al tipo del usuario logueado.
     * Tipos soportados en BD: ADMIN, EMPLEADO, PROFESOR, ALUMNO.
     */
    private void navegarSegunTipo(Usuario u) {
        Ventana_PPAL ventana = Ventana_PPAL.getInstancia();
        if (ventana == null) {
            mostrarError("Error interno: ventana principal no disponible.");
            return;
        }
 
        String tipo = u.getTipo() == null ? "" : u.getTipo().toUpperCase();
        switch (tipo) {
            case "ADMIN":
                ventana.mostrar(new Panel_administrador());
                break;
            case "EMPLEADO":
            case "PROFESOR":
                // No existe Panel_Empleado por ahora; un empleado opera con
                // las mismas herramientas que un docente.
                // Si despues crean un Panel_Empleado, mover el case EMPLEADO arriba.
                ventana.mostrar(new Panel_Docente());
                break;
            case "ALUMNO":
                ventana.mostrar(new Panel_Alumno());
                break;
            default:
                logger.warning("Tipo de usuario no reconocido: " + tipo);
                mostrarError("Rol no reconocido: " + tipo);
                SessionManager.cerrarSesion();
        }
    }
 
    private void mostrarError(String mensaje) {
        label_ayuda.setText(mensaje);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        label_ayuda = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campo_login_carnet = new javax.swing.JTextField();
        campo_login_password = new javax.swing.JPasswordField();
        boton_login_acceder = new javax.swing.JButton();

        setBackground(new java.awt.Color(11, 19, 43));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1280, 665));
        setMinimumSize(new java.awt.Dimension(1280, 665));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 665));

        jLabel1.setBackground(new java.awt.Color(11, 19, 43));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Biblioteca Virtual");

        label_ayuda.setBackground(new java.awt.Color(11, 19, 43));
        label_ayuda.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        label_ayuda.setForeground(new java.awt.Color(255, 255, 255));
        label_ayuda.setText("Ayuda");

        jLabel2.setBackground(new java.awt.Color(11, 19, 43));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¡Bienvenido a tu");

        jLabel3.setBackground(new java.awt.Color(11, 19, 43));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Biblioteca Virtual!");

        jTextArea4.setBackground(new java.awt.Color(11, 19, 43));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea4.setRows(3);
        jTextArea4.setText("Explora, descubre y accede a miles de libros,\n revistas y recursos académicos desde \ncualquier lugar y en cualquier momento.");
        jTextArea4.setAutoscrolls(false);
        jTextArea4.setBorder(null);
        jTextArea4.setCaretColor(new java.awt.Color(11, 19, 43));
        jTextArea4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(jTextArea4);

        jPanel1.setBackground(new java.awt.Color(11, 19, 43));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));

        jLabel4.setBackground(new java.awt.Color(11, 19, 43));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Iniciar Sesión");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario/Carnet");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contraseña");

        campo_login_carnet.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        campo_login_password.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        boton_login_acceder.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        boton_login_acceder.setText("ACCEDER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7)
                        .addGap(18, 32, Short.MAX_VALUE)
                        .addComponent(campo_login_password, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(campo_login_carnet, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(boton_login_acceder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campo_login_carnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(campo_login_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(boton_login_acceder, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_ayuda, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(label_ayuda))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("panel_bienvenida");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_login_acceder;
    private javax.swing.JTextField campo_login_carnet;
    private javax.swing.JPasswordField campo_login_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel label_ayuda;
    // End of variables declaration//GEN-END:variables
}
