
package com.mediateca.vistas.formularios;
 
import com.mediateca.dao.UsuarioDAO;
import com.mediateca.model.Usuario;
import com.mediateca.vistas.Panel_administrador;
import com.mediateca.vistas.Ventana_PPAL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
 
/**
 *
 * @author Francisco De la O Gonzalez - DG200722
 */
public class Panel_ingresoadmin extends javax.swing.JPanel {
 
    private static final Logger logger = Logger.getLogger(Panel_ingresoadmin.class.getName());
    private static final String REGEX_EMAIL = "^[\\w.\\-]+@[\\w.\\-]+\\.[A-Za-z]{2,}$";
 
    private final UsuarioDAO usuarioDAO = new UsuarioDAO();
 
    /**
     * Creates new form Panel_ingresoalum
     */
    public Panel_ingresoadmin() {
        initComponents();
        cablearEventos();
    }
 
    private void cablearEventos() {
        boton_Registrar.addActionListener(e -> registrar());
        boton_limpiarcampos.addActionListener(e -> limpiarCampos());
        botn_cancelar.addActionListener(e -> volverAlMenu());
        jButton3.addActionListener(e -> revisarEmailEnBD()); // boton "REVISION"
    }
 
    /**
     * Valida campos y registra un nuevo administrador.
     * Campos sin backend (no se persisten): carnet, usuario, estado.
     * Se guardan: nombre, email, contrasena, tipo (=ADMIN), telefono.
     */
    private void registrar() {
        String nombre   = campo_nombrecomp.getText().trim();
        String email    = campo_email.getText().trim();
        String password = campo_contrase.getText().trim();
        String telefono = campo_telefono.getText().trim();
 
        if (nombre.isEmpty() || email.isEmpty() || password.isEmpty()) {
            mostrarError("Nombre, correo y contraseña son obligatorios.");
            return;
        }
        if (!email.matches(REGEX_EMAIL)) {
            mostrarError("El correo no tiene un formato válido.");
            return;
        }
        if (password.length() < 4) {
            mostrarError("La contraseña debe tener al menos 4 caracteres.");
            return;
        }
 
        try {
            if (usuarioDAO.existeEmail(email)) {
                mostrarError("Ya existe un usuario con ese correo.");
                return;
            }
 
            Usuario nuevo = new Usuario();
            nuevo.setNombre(nombre);
            nuevo.setEmail(email);
            nuevo.setContrasena(password);
            nuevo.setTipo("ADMIN");
            nuevo.setTelefono(telefono);
            // carrera queda null: un administrador no tiene carrera.
 
            if (usuarioDAO.insertar(nuevo)) {
                JOptionPane.showMessageDialog(this,
                    "Administrador registrado correctamente.",
                    "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
            } else {
                mostrarError("No se pudo registrar el administrador. Revisa los logs.");
            }
        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Error al registrar administrador", ex);
            mostrarError("Error de conexión: " + ex.getMessage());
        }
    }
 
    private void revisarEmailEnBD() {
        String email = campo_email.getText().trim();
        if (email.isEmpty()) {
            mostrarError("Ingresa un correo para revisarlo.");
            return;
        }
        try {
            boolean existe = usuarioDAO.existeEmail(email);
            JOptionPane.showMessageDialog(this,
                existe ? "El correo YA está registrado en la BD."
                       : "El correo está libre, puede usarse.",
                "Revisión de correo",
                existe ? JOptionPane.WARNING_MESSAGE : JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            logger.log(Level.SEVERE, "Error al revisar email", ex);
            mostrarError("Error de conexión: " + ex.getMessage());
        }
    }
 
    private void limpiarCampos() {
        campo_carnet.setText("");
        campo_nombrecomp.setText("");
        campo_email.setText("");
        campo_telefono.setText("");
        campo_user.setText("");
        campo_contrase.setText("");
        campo_estado.setText("");
        campo_nombrecomp.requestFocus();
    }
 
    private void volverAlMenu() {
        Ventana_PPAL.getInstancia().mostrar(new Panel_administrador());
    }
 
    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campo_carnet = new javax.swing.JTextField();
        campo_nombrecomp = new javax.swing.JTextField();
        campo_email = new javax.swing.JTextField();
        campo_telefono = new javax.swing.JTextField();
        campo_user = new javax.swing.JTextField();
        campo_contrase = new javax.swing.JTextField();
        campo_estado = new javax.swing.JTextField();
        boton_Registrar = new javax.swing.JButton();
        boton_limpiarcampos = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        botn_cancelar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Carnet");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nombre Completo");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Correo");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Telefono");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Usuario");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Contraseña");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Estado");

        campo_carnet.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campo_carnet.addActionListener(this::campo_carnetActionPerformed);

        campo_nombrecomp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        campo_email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        campo_telefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        campo_user.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        campo_contrase.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        campo_estado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        boton_Registrar.setText("REGISTRAR");
        boton_Registrar.addActionListener(this::boton_RegistrarActionPerformed);

        boton_limpiarcampos.setText("LIMPIAR");

        jButton3.setText("REVISION");

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel12.setText("REGISTRO DE NUEVO ADMINISTRADOR");

        botn_cancelar.setText("cancelar");
        botn_cancelar.addActionListener(this::botn_cancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(campo_nombrecomp, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campo_user, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                    .addComponent(campo_contrase, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                    .addComponent(campo_estado, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                    .addComponent(campo_email, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                    .addComponent(campo_carnet, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton3)
                        .addGap(53, 53, 53)
                        .addComponent(boton_Registrar)
                        .addGap(53, 53, 53)
                        .addComponent(boton_limpiarcampos)
                        .addGap(36, 36, 36)
                        .addComponent(botn_cancelar)))
                .addContainerGap(410, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campo_carnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campo_nombrecomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campo_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_contrase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campo_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(208, 208, 208)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(boton_Registrar)
                    .addComponent(boton_limpiarcampos)
                    .addComponent(botn_cancelar))
                .addGap(58, 58, 58))
        );

        getAccessibleContext().setAccessibleName("Panel_ingresouser");
    }// </editor-fold>//GEN-END:initComponents

    private void boton_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_RegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_RegistrarActionPerformed

    private void campo_carnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_carnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_carnetActionPerformed

    private void botn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botn_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botn_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botn_cancelar;
    private javax.swing.JButton boton_Registrar;
    private javax.swing.JButton boton_limpiarcampos;
    private javax.swing.JTextField campo_carnet;
    private javax.swing.JTextField campo_contrase;
    private javax.swing.JTextField campo_email;
    private javax.swing.JTextField campo_estado;
    private javax.swing.JTextField campo_nombrecomp;
    private javax.swing.JTextField campo_telefono;
    private javax.swing.JTextField campo_user;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
